This is the homework for week 2! The prompt is to use NumPy (or sagemath) to determine if a list of vectors forms an orthogonal / orthonormal basis for a vector space, compute inner products, multiply matrices, and compute LU and spectral decompositions.

Problem 1: Build a function to take two vectors with real-valued entries and compute their inner product. 

In [42]:
def ip(v1,v2):
    ip_out = 0
    for i in range (len(v1)):
        ip_out += v1[i] * v2[i]

    return ip_out
a = [1, 2, -1]
b = [4, -1, 2]

print(f'The inner product of {a} and {b} is {ip(a,b)}.')

The inner product of [1, 2, -1] and [4, -1, 2] is 0.


Problem 2: Build a function which checks if two matrices can be multiplied and then multiplies them.

In [43]:
import numpy as np

A = np.array( [[3,1],
            [-1,0]] )
print(A)
B = np.array( [[3,2], 
            [-1,0]] )
print(B)


def canMult(A,B):
    if np.shape(A)[1] == np.shape(B)[0]:
        return True
    else:
        return False
    
def mult(A,B):

    if canMult(A,B):
        return True
    else:
        return False

result_matrix = np.matmul(A, B)

print(result_matrix)
print('Matrix Multiplication is possible. ')



[[ 3  1]
 [-1  0]]
[[ 3  2]
 [-1  0]]
[[ 8  6]
 [-3 -2]]
Matrix Multiplication is possible. 


Problem 3: Build a function which takes A and computes $A^T$.

In [44]:
"""
( [1,2], <--- abritrary 2x2 matrix, 
[3,4] )


import numpy as np
A = np.array( [[3,1], 
            [-1,0]] )

print(A)[0]
"""
import numpy as np

def transpose(A):
    m, n = np.shape(A)        # rows, cols
    T = np.zeros((n, m))      # transpose
    
    for i in range(m):        # rows
        for j in range(n):    # columns
            T[j, i] = A[i, j] # flip 
    
    return T

A = np.array([[3, 2], 
              [-1, 0], 
              [3, 3]])

print("Original A:\n", A)
print("Transpose of A:\n", transpose(A))


Original A:
 [[ 3  2]
 [-1  0]
 [ 3  3]]
Transpose of A:
 [[ 3. -1.  3.]
 [ 2.  0.  3.]]


Problem 4: Build a function which determines if a list of vectors is an orthogonal or orthonormal basis by computing $A^T A$ and checking if it is diagonal / I. (Hint: Use your function from problem 3!)

In [45]:
import numpy as np

def transpose(A):
    m, n = np.shape(A) # m - rows, n - columns
    T = np.zeros((n, m))
    for i in range(m):
        for j in range(n):
            T[j, i] = A[i, j]
    return T

def check_basis(A):

    A_T = transpose(A)
    ATA = np.matmul(A_T, A)

    # check if ATA is diagonal (i.e., perpendicular or orthogonal)
    is_diagonal = np.allclose(ATA, np.diag(np.diagonal(ATA)))

    # check if ATA is identity
    is_identity = np.allclose(ATA, np.identity(A.shape[1]))

    if is_identity:
        return "The vectors form an orthonormal basis."
    elif is_diagonal:
        return "The vectors form an orthogonal (but not orthonormal) basis."
    else:
        return "The vectors are neither orthogonal nor orthonormal."

# Orthonormal basis in R^2
A = np.array([[1, 0],
              [0, 1]])
print(check_basis(A))   # orthonormal

# Orthogonal but not orthonormal
B = np.array([[2, 0],
              [0, 3]])
print(check_basis(B))   # orthogonal only (not of unit length)

# Not orthogonal
C = np.array([[1, 1],
              [1, 0]])
print(check_basis(C))   # neither


The vectors form an orthonormal basis.
The vectors form an orthogonal (but not orthonormal) basis.
The vectors are neither orthogonal nor orthonormal.


Problem 5: Use Numpy's internal tools to compute the eigenvectors and eigenvalues of A, and then build a function which outputs the spectral decomposition of A.

In [46]:
def spectral_decomposition(A):
    # eigenvalues & eigenvectors
    eigvals, eigvecs = np.linalg.eig(A)
    # diagonal matrix of eigenvalues
    Lambda = np.diag(eigvals)
    # eigenvector matrix
    Q = eigvecs
    # inverse of Q
    Q_inv = np.linalg.inv(Q)
    
    # reconstruct A using spectral decomposition
    A_reconstructed = Q @ Lambda @ Q_inv
    
    return {
        "Eigenvalues": eigvals,
        "Eigenvectors": eigvecs,
        "A_synth": A_reconstructed
    }

result = spectral_decomposition(A)
for key, value in result.items():
    print(f"{key}:\n{value}\n")


Eigenvalues:
[1. 1.]

Eigenvectors:
[[1. 0.]
 [0. 1.]]

A_synth:
[[1. 0.]
 [0. 1.]]

